### ISSUE TITLE
[BUG] no disk info display

### ISSUE THREAD

**Issue by Argon-D** [swizzin/swizzin#1030]
### What happened?

hello guys , I have thi situation : 

https://ibb.co/cb5tn3t

Can't display the size of the drive on disk info windows. I've tried to reinstall "panel" with no luck 

Is there a fix?

Thanks in advance!

### Swizzin commit

last version

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Can't display the size of the drive on disk info windows. I've tried to reinstall "panel" with no luck
```

**Comment by liaralabs** [comment]
One user recently reported that they had issues while they had a USB drive plugged into their system.

Conversely, consider checking the panel logs for more info or to see if any exceptions are being thrown:

```
journalctl -u panel
```

**Comment by Argon-D** [comment]
yes I have plugged usb adapter nvme driver

**Comment by liaralabs** [comment]
Can you try unplugging it to see if the issue goes away? The panel may need to have some updates to help accommodate these circumstances, but it's not something I really have access to test and reproduce

**Comment by Argon-D** [comment]
OK let me try

**Comment by Argon-D** [comment]
Can't remove one usb driver atm ( I have actually 2 connected) , If I remove one, the bug still there

**Comment by flying-sausages** [comment]
Can you post the picture into the comments here? The original link expired

**Comment by Jimmy062006** [comment]
The original image is missing so not sure if this is the same issue but I experienced this issue recently and found that if 1 single mount point is in accessible to the python panel it will error out and produce the below error.


![image](https://github.com/swizzin/swizzin/assets/4639349/285c08e0-47df-43bb-8235-49a8f45835e5)

![image](https://github.com/swizzin/swizzin/assets/4639349/5e668806-0cd3-4203-96c0-5ab402a5e231)

**Comment by DrAnthonyYbara** [comment]
I have the same issue, here are the logs:
<img width="484" alt="Screenshot 2023-08-08 at 18 00 33" src="https://github.com/swizzin/swizzin/assets/65922574/d22f1e04-0df1-4bb1-8b9d-c4cccef8e85b">

opt/.venv/swizzin/lib/python3.8/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicit
Aug 08 17:43:38 box-device python[29088]:   warnings.warn(
Aug 08 17:43:38 box-device python[29088]: ERROR:swizzin:Exception on /stats/disk [GET]
Aug 08 17:43:38 box-device python[29088]: Traceback (most recent call last):
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
Aug 08 17:43:38 box-device python[29088]:     response = self.full_dispatch_request()
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
Aug 08 17:43:38 box-device python[29088]:     rv = self.handle_user_exception(e)
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
Aug 08 17:43:38 box-device python[29088]:     rv = self.dispatch_request()
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
Aug 08 17:43:38 box-device python[29088]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Aug 08 17:43:38 box-device python[29088]:   File "/opt/swizzin/core/htpasswd.py", line 209, in decorated
Aug 08 17:43:38 box-device python[29088]:     return func(*args, **kwargs)
Aug 08 17:43:38 box-device python[29088]:   File "swizzin.py", line 350, in disk_free
Aug 08 17:43:38 box-device python[29088]:     total, used, free, usage = disk_usage(mount)
Aug 08 17:43:38 box-device python[29088]:   File "/opt/swizzin/core/util.py", line 236, in disk_usage
Aug 08 17:43:38 box-device python[29088]:     total, used, free = shutil.disk_usage(location)
Aug 08 17:43:38 box-device python[29088]:   File "/usr/lib/python3.8/shutil.py", line 1258, in disk_usage
Aug 08 17:43:38 box-device python[29088]:     st = os.statvfs(path)
Aug 08 17:43:38 box-device python[29088]: PermissionError: [Errno 13] Permission denied: ‘/media/example/External\\ExampleDrive’
Aug 08 17:43:38 box-device python[29088]: ERROR:swizzin:Exception on /stats/vnstat [GET]
Aug 08 17:43:38 box-device python[29088]: Traceback (most recent call last):
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
Aug 08 17:43:38 box-device python[29088]:     response = self.full_dispatch_request()
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
Aug 08 17:43:38 box-device python[29088]:     rv = self.handle_user_exception(e)
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
Aug 08 17:43:38 box-device python[29088]:     rv = self.dispatch_request()
Aug 08 17:43:38 box-device python[29088]:   File "/opt/.venv/swizzin/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
Aug 08 17:43:38 box-device python[29088]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Aug 08 17:43:38 box-device python[29088]:   File "/opt/swizzin/core/htpasswd.py", line 209, in decorated
