### ISSUE TITLE
[BUG] Network info doesn't work

### ISSUE THREAD

**Issue by matthieuki** [swizzin/swizzin#1077]
### What happened?

Hi,

My seedbox encounter a little bug since I've update my Esxi server.
The network shows me just the live information but not my history.
I've put the log in the ticket, but I don't know where I must search to resolve the problem

Can you help me ?

Tks !

### Swizzin commit

3922dc7

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
sept. 17 10:33:53 xxx.xxx.xx python[3765]: ERROR:swizzin:Exception on /stats/vnstat [GET]
sept. 17 10:33:53 xxx.xxx.xx python[3765]: Traceback (most recent call last):
sept. 17 10:33:53 xxx.xxx.xx python[3765]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
sept. 17 10:33:53 xxx.xxx.xx python[3765]:     response = self.full_dispatch_request()
sept. 17 10:33:53 xxx.xxx.xx python[3765]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
sept. 17 10:33:53 xxx.xxx.xx python[3765]:     rv = self.handle_user_exception(e)
sept. 17 10:33:53 xxx.xxx.xx python[3765]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
sept. 17 10:33:53 xxx.xxx.xx python[3765]:     rv = self.dispatch_request()
sept. 17 10:33:53 xxx.xxx.xx python[3765]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
sept. 17 10:33:53 xxx.xxx.xx python[3765]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
sept. 17 10:33:53 xxx.xxx.xx python[3765]:   File "/opt/swizzin/core/htpasswd.py", line 209, in decorated
sept. 17 10:33:53 xxx.xxx.xx python[3765]:     return func(*args, **kwargs)
sept. 17 10:33:53 xxx.xxx.xx python[3765]:   File "/opt/swizzin/swizzin.py", line 317, in vnstat
sept. 17 10:33:53 xxx.xxx.xx python[3765]:     lasthour = vnstat_info['interfaces'][0]['traffic']['hour'][-2]["id"]
sept. 17 10:33:53 xxx.xxx.xx python[3765]: IndexError: list index out of range
```

**Comment by liaralabs** [comment]
This is a common problem and not really a swizzin bug, but a vnstat issue. Replace enp7s0 with your own NIC device.

Just something like a `vnstat -d -i enp7s0` should show you if anything is in the database for this nic

If no db then something like `vnstat -i enp7s0 -u` should create the db file

Then fix perms:  `chown -R vnstat:vnstat /var/lib/vnstat`

Restart vnstat `systemctl restart vnstat`

**Comment by matthieuki** [comment]
Tks for the reply.
I've a database for Vnstat and have deleted for reset it.
But I've always the same logs when I restart panel 

This the Vnstat logs : 

```plaintext
sept. 17 15:45:42 xxx.xxx.xx vnstatd[7270]: Info: SIGTERM received, exiting.
sept. 17 15:45:42 xxx.xxx.xx systemd[1]: Stopping vnStat network traffic monitor...
sept. 17 15:45:42 xxx.xxx.xx systemd[1]: vnstat.service: Deactivated successfully.
sept. 17 15:45:42 xxx.xxx.xx systemd[1]: Stopped vnStat network traffic monitor.
sept. 17 15:45:42 xxx.xxx.xx systemd[1]: Started vnStat network traffic monitor.
sept. 17 15:45:42 xxx.xxx.xx vnstatd[7482]: Info: vnStat daemon 2.9 started. (pid:7482 uid:113 gid:118 64-bit)
sept. 17 15:45:42 xxx.xxx.xx vnstatd[7482]: Info: Monitoring (1): ens160 (10000 Mbit)
```

The out of Vnstat

```plaintext
Database updated: 2023-09-17 16:00:00

   ens160 since 2023-09-17

          rx:  69,86 MiB      tx:  767,72 MiB      total:  837,58 MiB

   monthly
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
       2023-09     69,86 MiB |  767,72 MiB |  837,58 MiB |    4,88 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated    123,60 MiB |    1,35 GiB |    1,47 GiB |

   daily
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
         today     69,86 MiB |  767,72 MiB |  837,58 MiB |  121,98 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated    104,79 MiB |    1,12 GiB |    1,23 GiB |
```

And Panel logs :

```plaintext
sept. 17 15:56:03 xxx.xxx.xx python[7539]: ERROR:swizzin:Exception on /stats/vnstat [GET]
sept. 17 15:56:03 xxx.xxx.xx python[7539]: Traceback (most recent call last):
sept. 17 15:56:03 xxx.xxx.xx python[7539]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
sept. 17 15:56:03 xxx.xxx.xx python[7539]:     response = self.full_dispatch_request()
sept. 17 15:56:03 xxx.xxx.xx python[7539]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
sept. 17 15:56:03 xxx.xxx.xx python[7539]:     rv = self.handle_user_exception(e)
sept. 17 15:56:03 xxx.xxx.xx python[7539]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
sept. 17 15:56:03 xxx.xxx.xx python[7539]:     rv = self.dispatch_request()
sept. 17 15:56:03 xxx.xxx.xx python[7539]:   File "/opt/.venv/swizzin/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
sept. 17 15:56:03 xxx.xxx.xx python[7539]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
sept. 17 15:56:03 xxx.xxx.xx python[7539]:   File "/opt/swizzin/core/htpasswd.py", line 209, in decorated
sept. 17 15:56:03 xxx.xxx.xx python[7539]:     return func(*args, **kwargs)
sept. 17 15:56:03 xxx.xxx.xx python[7539]:   File "/opt/swizzin/swizzin.py", line 317, in vnstat
sept. 17 15:56:03 xxx.xxx.xx python[7539]:     lasthour = vnstat_info['interfaces'][0]['traffic']['hour'][-2]["id"]
sept. 17 15:56:03 xxx.xxx.xx python[7539]: IndexError: list index out of range
```

**Comment by matthieuki** [comment]
Finally it's good ! I just had to wait a little bit

Thank you !
