### ISSUE TITLE
[BUG] Unable to restart services from panel -- Uncaught ReferenceError: timer is not defined

### ISSUE THREAD

**Issue by imthenachoman** [swizzin/swizzin#1087]
### What happened?

Steps to reproduce:

1. Click on `restart` next to service

Expected results:

It should restart the service but it does not.

Actual results:

I can see the following error in the browser's developer console:

```
swizzin.js:14 Uncaught ReferenceError: timer is not defined
    at Object.success (swizzin.js:14:22)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)
```

### Swizzin commit

3922dc7

### What OS are you using?

Debian 12 (Bookworm)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
swizzin.js:14 Uncaught ReferenceError: timer is not defined
    at Object.success (swizzin.js:14:22)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)
```
```

**Comment by liaralabs** [comment]
Is this issue still relevant? I cannot reproduce your issues.
