### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bennohef** [swizzin/swizzin#1158]
### What happened?

Deluge 2.1.1 with libtorrent v1.2 do not start. Seems some installation issue with deluged package (libtorrent).

Installation do not fail, but deluged just do not starts.

### Swizzin commit

953e4c7

### What OS are you using?

Debian 12 (Bookworm)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/_libtorrent.py", line 21, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/_libtorrent.py", line 24, in <module>
    import libtorrent as lt
ModuleNotFoundError: No module named 'libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/deluged", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.1.1', 'gui_scripts', 'deluged')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/deluge/core/daemon_entry.py", line 87, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/usr/lib/python3/dist-packages/deluge/core/daemon.py", line 19, in <module>
    from deluge.core.core import Core
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 26, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/usr/lib/python3/dist-packages/deluge/_libtorrent.py", line 26, in <module>
    raise LibtorrentImportError('No libtorrent library found: %s' % (ex))
deluge.error.LibtorrentImportError: No libtorrent library found: No module named 'libtorrent'
```

**Comment by AncientVamp** [comment]
I have the same issue. #1146

**Comment by slimequeen3251** [comment]
> Fixed it. Just change boost lib. version. By default it's 1.74, change to latest one on today (1.85).
> 
> It can be changed in "/etc/swizzin/sources/functions/libtorrent", there you will find "BOOST_VERSION" variable in boostrap function.

When you do this and recompile with : sudo box upgrade deluge 

It overwrites those changes as it repulls the swizzin repo. How do you make it use the new boost version?

**Comment by liaralabs** [comment]
This has been fixed in develop
