### ISSUE TITLE
[BUG] Tautulli Setup 

### ISSUE THREAD

**Issue by checkso** [swizzin/swizzin#1195]
### What happened?

**Steps to reproduce:**

1. `box install tautulli`

**What I did to try to understand the issue:**
I check all logs, and during the installation, the installer hangs at step "setting up nginx".
After checking what the installer does it, looks like it wants to configure the file  _/opt/tautulli/config.ini_
This file is not there, so it keeps in the loop indefinitely. 
I tried to create the file manually, than the installer finishes successfully, but the application is not starting.
See errorlog below.

### Swizzin commit

0167911

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
python3[287599]: Traceback (most recent call last):
python3[287599]:   File "/opt/tautulli/Tautulli.py", line 39, in <module>
python3[287599]:     import plexpy
python3[287599]:   File "/opt/tautulli/plexpy/__init__.py", line 33, in <module>
python3[287599]:     from apscheduler.schedulers.background import BackgroundScheduler
python3[287599]:   File "/opt/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
python3[287599]:     from pkg_resources import get_distribution, DistributionNotFound
python3[287599]: ModuleNotFoundError: No module named 'pkg_resources'
systemd[1]: tautulli.service: Control process exited, code=exited, status=1/FAILURE
```

**Comment by dpd696** [comment]
Did you find a solution for this issue? I setup up a brand new server and recieving the same error.

**Comment by schuelepatrick** [comment]
@dpd696 
try creating the `/opt/tautulli/config.ini` file manually and after that:
`bash /usr/local/bin/swizzin/nginx/tautulli.sh`
