### ISSUE TITLE
[BUG]  Flood - node gyp requires python2 to build so build fails but appears successful

### ISSUE THREAD

**Issue by userdocs** [swizzin/swizzin#787]
### What happened?

Steps to reproduce:

1. Install package `box install rtorrent flood`
2. Go to '....'
3. Error 'none'

```bash
root@swizzin:~# box install flood
INFO    Installing flood
DOCS    Further reference: https://swizzin.ltd/applications/flood
...     Installing npm
...     Performing installation of 2 apt packages
        (nodejs build-essential)
        ✔   Apt install complete
        ✔   Npm installed
...     Installing node-gyp
        ✔   Done
...     Configuring flood for username
...     Cloning source code
        ✔   Source cloned
...     Building Flood for username. This might take some time...
        ✔   Flood built for username
INFO    Flood port for username is 4496
        ✔   Flood for username configured
SUCCESS Flood installed
```
Expected results:

### Swizzin commit

d1a35a7

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/linux-x64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 postinstall /home/username/.flood/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/username/.flood/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/username/.flood/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/username/.flood/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/username/.flood/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/username/.flood/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/username/.flood/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/username/.flood/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/username/.flood/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/username/.flood/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/username/.flood/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/username/.flood/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/username/.flood/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/username/.flood/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/username/.flood/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/username/.flood/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/username/.flood/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/username/.flood/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/username/.flood/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/username/.flood/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/username/.flood/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/username/.flood/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/username/.flood/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/username/.flood/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/username/.flood/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/username/.flood/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/username/.flood/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:191:21)
gyp ERR! System Linux 5.10.0-9-amd64
gyp ERR! command "/usr/bin/node" "/home/username/.flood/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/username/.flood/node_modules/node-sass
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2021-10-27T13_25_43_290Z-debug.log
```

**Comment by liaralabs** [comment]
Fixed in master with new jesec fork.
