### ISSUE TITLE
[BUG] Ombi is keep crashing

### ISSUE THREAD

**Issue by nikitah4x** [swizzin/swizzin#794]
### What happened?

Steps to reproduce:

1. Install package 'box install ombi'
2. Go to 'Swizzin Panel and click on ombi'
3. Error '502 Bad Gateway'

Expected results:
You will get 502 Bad Gateway

### Swizzin commit

d1a35a7

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
-- A start job for unit ombi.service has finished successfully.
-- 
-- The job identifier is 17209.
Nov 01 17:50:16 shornamazitv Ombi[20431]: Hello, welcome to Ombi
Nov 01 17:50:16 shornamazitv Ombi[20431]: Valid options are:
Nov 01 17:50:16 shornamazitv Ombi[20431]: Ombi 4.0.1342
Nov 01 17:50:16 shornamazitv Ombi[20431]: Copyright (C) 2021 Ombi
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
Nov 01 17:50:16 shornamazitv Ombi[20431]:                URL prefixes to which the server should respond. For example,
Nov 01 17:50:16 shornamazitv Ombi[20431]:                http://localhost:123. Use "localhost" to indicate that the server
Nov 01 17:50:16 shornamazitv Ombi[20431]:                should listen for requests on any IP address or hostname using
Nov 01 17:50:16 shornamazitv Ombi[20431]:                the specified port and protocol (for example,
Nov 01 17:50:16 shornamazitv Ombi[20431]:                http://localhost:5000). The protocol (http:// or https://) must
Nov 01 17:50:16 shornamazitv Ombi[20431]:                be included with each URL. Supported formats vary between
Nov 01 17:50:16 shornamazitv Ombi[20431]:                servers.
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --storage    Storage path, where we save the logs and database
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --baseurl    The base URL for reverse proxy scenarios
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --demo       Demo mode, you will never need to use this, fuck that fruit
Nov 01 17:50:16 shornamazitv Ombi[20431]:                company...
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --migrate    Will run the migrations then exit the application
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --help       Display this help screen.
Nov 01 17:50:16 shornamazitv Ombi[20431]:   --version    Display version information.
Nov 01 17:50:16 shornamazitv Ombi[20431]: Base Url: /ombi
Nov 01 17:50:17 shornamazitv Ombi[20431]: Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: EmbyEpisode'.
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Ombi.Store.Context.Sqlite.OmbiSqliteContext..ctor(DbContextOptions`1 options)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Ombi.Program.Main(String[] args)
Nov 01 17:50:17 shornamazitv Ombi[20431]:    at Ombi.Program.<Main>(String[] args)
Nov 01 17:50:17 shornamazitv systemd[1]: ombi.service: Main process exited, code=killed, status=6/ABRT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit ombi.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 6.
Nov 01 17:50:17 shornamazitv systemd[1]: ombi.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit ombi.service has entered the 'failed' state with result 'signal'.
```

**Comment by brettpetch** [comment]
looks like an ombi issue not a swizzin issue.
