### ISSUE TITLE
[BUG] Internal Server Error after downloading 'Throttle' Plugin for ruTorrent

### ISSUE THREAD

**Issue by Heavybullets8** [swizzin/swizzin#812]
### What happened?

Steps to reproduce:

1. Install both rTorrent (any version) + Rutorrent
2. run `sudo box rtx` Ok > Plugins > Install Plugins > Throttle
3. Navigate to your ruTorrent Page
4. Then you will see the error `[15.01.2022 03:25:43] Bad response from server: (500 [error,getplugins]) Internal Server Error`

Expected results:
ruTorrent correctly loads the 'Throttle' plugin, along with the rest of its UI. 

### Swizzin commit

9ef0807

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
Nginx Logs
2022/01/15 04:25:43 [error] 833#833: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'FileUtil' not found in /srv/rutorrent/plugins/throttle/throttle.php:4
Stack trace:
#0 /srv/rutorrent/plugins/throttle/init.php(2): require_once()
#1 /srv/rutorrent/php/getplugins.php(495): require_once('/srv/rutorrent/...')
#2 {main} thrown in /srv/rutorrent/plugins/throttle/throttle.php on line 4" while reading response header from upstream, client: 69.69.69.69, server: SEEDBOXDOMAIN.COM, request: "GET /rutorrent/php/getplugins.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "SEEDBOXDOMAIN.COM", referrer: "https://SEEDBOXDOMAIN.COM"

ruTorrent Error Message 
[15.01.2022 03:25:43] Bad response from server: (500 [error,getplugins]) Internal Server Error

PHP Version 7.4.25
rTorrent Version 9.6 (but any of them produce this message)
ruTorrent Version 3.10

This is a new install that I just completed today (14 Jan 2022).
```

**Comment by Heavybullets8** [comment]
closing this due to duplication. I over-looked the issue about this directly below mine somehow.. Sorry about that.
