### ISSUE TITLE
[BUG] Failed to get the list of torrents: Response contains invalid XML (rutorrent/httprpc/*arrs)

### ISSUE THREAD

**Issue by bleugray** [swizzin/swizzin#817]
### What happened?

I am receiving this message in Sonarr, Radarr and Lidarr appears to have started on or a little before Jan 17, 2022

This error is the listed under the system/status section in the above apps

**_Unable to communicate with rTorrent (https://xxx.xxx.com/rutorrent/plugins/httprpc/action.php). Response from server does not contain valid XML_**

When adding the download client and using the test feature I receive the following error.  This has worked for months previously.

"**_Failed to get the list of torrents: Response contains invalid XML_**"

What other info would be helpful? rtorrent/rutorrent are hosted on a seedbox while Sonarr, Radarr and Lidarr are hosted locally.

I have built  a new server and tested everything locally with the same result.  
I am receiving the same result when using both methods **_RPC Mount: /<username> OR /rutorrent/plugins/httprpc/action.php_**

### Swizzin commit

 9ef0807

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
Is your seedbox hosted on a swizzin installation as well?

**Comment by bleugray** [comment]
no it was a short period.  now a dedicated hosted at hetzner

**Comment by liaralabs** [comment]
You've said the system/status gives you that error message, but what about the log entry from any of the applications when you try testing the connection to the rpc endpoint?

**Comment by bleugray** [comment]
from Radarr

`**Message**
Failed to get torrents: Response from server does not contain valid XML.

**Exception**
CookComputing.XmlRpc.XmlRpcIllFormedXmlException: Response from server does not contain valid XML.
 ---> System.Xml.XmlException: '', hexadecimal value 0x1B, is an invalid character. Line 8560, position 16.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
   --- End of inner exception stack trace ---
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm, Type returnType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(MethodInfo mi, Object[] parameters)
   at XmlRpcProxy33984026-809e-4f2f-b7c3-89332498153c.TorrentMulticall(String[] parameters)
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.<>c__DisplayClass3_0.<GetTorrents>b__0() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 77
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T](Func`1 task) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 262
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetTorrents(RTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 77
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.TestGetTorrents() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:line 227`

and

**Comment by liaralabs** [comment]
What are your connection settings in Radarr?



Is your ssl certificate valid? Is SSL verification set properly? On if your cert is valid and off if it is self-signed.

By default we only disable SSL verification for localhost addresses.

https://github.com/Radarr/Radarr/issues/5516

**Comment by bleugray** [comment]
SSL is valid using Letsencrypt (just reconfigured to be sure)

Radarr and Sonarr are both configured with the hostname, port 443, SSL checked, URL path is the /"username"

when configuring Radarr locally on the seedbox alongside ru/rtorrent I get the same error.  (localhost, 443, etc)

**Comment by liaralabs** [comment]
Can you take a screenshot of the configuration with advanced options enabled and censor any sensitive bits?

You are connecting to the domain directly and not the IP?

Sorry for all the dumb basic questions, but this error is likely coming down to some sort of configuration issue.

What version of Radarr are you using locally?

**Comment by bleugray** [comment]
correct domain directly.  have tried IP also
radarr v3.2.2.5080
rutorrent v3.10 / rtorrent 0.9.8

![image](https://user-images.githubusercontent.com/13936337/150740504-c1d97b6e-42a8-47a7-9a4b-532616aef02c.png)

**Comment by stickz** [comment]
**You can not use httprpc for features which require an XML response. This outputs a JSON response.**

**Comment by bakerboy448** [comment]
Correct - \*arrs need the xmlrpc endpoint as the helptext notes.

**Comment by bleugray** [comment]
thanks for all the assistance.  very odd this "seemed" to be working for months at least it wasn't giving errors.  my local install is using RPC and is working.  I will configure RPC on the swizzin server and see how it goes.

**Comment by bleugray** [comment]
what is the trick to activate rpc vs httprpc? (does httprpc need to be disable due to an conflicts?)

I have added rpc via rtx but don't seem to be able to make a connection to it.  what additional configuration would need to be done.  is there a guide you can point me to?

**Comment by liaralabs** [comment]
The example in your screenshot is the correct usage for the RPC mount: `/rutorrent/plugins/rpc/rpc.php`

Just be aware that there are some issues in swizzin main branch at the moment. If your ruTorrent installation is old, rtx is currently pulling new and refactored 4.0 plugins which may or may not be compatible with older installations

**Comment by bleugray** [comment]
does this need to be enabled in the config.php?

//$XMLRPCMountPoint = "/RPC2"; // DO NOT DELETE THIS LINE!!! DO NOT COMMENT THIS LINE!!!

**Comment by cp-samantha** [comment]
No, it's set on a per user basis in `/srv/rutorrent/conf/users/username/config.php`
