### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by brettpetch** [swizzin/swizzin#837]
### What happened?

Package Issues with Panel.

### Swizzin commit

 dc64b75

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
/opt/.venv/swizzin/bin/python swizzin.py
Traceback (most recent call last):
  File "/opt/swizzin/swizzin.py", line 3, in <module>
    from core.htpasswd import HtPasswdAuth
  File "/opt/swizzin/core/htpasswd.py", line 12, in <module>
    from itsdangerous import JSONWebSignatureSerializer as Serializer
ImportError: cannot import name 'JSONWebSignatureSerializer' from 'itsdangerous' (/opt/.venv/swizzin/lib/python3.9/site-packages/itsdangerous/__init__.py)
```

**Comment by dctorrent1337** [comment]
I can replicate the same problem on ubuntu 20.04.

The dependency seems to be installed though:

```
root@dest:/opt/swizzin# source /opt/.venv/swizzin/
bin/        include/    lib/        lib64/      pyvenv.cfg  share/      
root@dest:/opt/swizzin# source /opt/.venv/swizzin/bin/activate
(swizzin) root@dest:/opt/swizzin# pip install itsdangerous
Requirement already satisfied: itsdangerous in /opt/.venv/swizzin/lib/python3.8/site-packages (2.1.0)
```

journalctl log
```
Feb 18 15:00:56 dest systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 15:00:56 dest systemd[1]: panel.service: Failed with result 'exit-code'.
Feb 18 15:00:57 dest systemd[1]: panel.service: Scheduled restart job, restart counter is at 4.
Feb 18 15:00:57 dest systemd[1]: Stopped swizzin panel service.
Feb 18 15:00:57 dest systemd[1]: Started swizzin panel service.
Feb 18 15:00:57 dest python[42071]: Traceback (most recent call last):
Feb 18 15:00:57 dest python[42071]:   File "swizzin.py", line 3, in <module>
Feb 18 15:00:57 dest python[42071]:     from core.htpasswd import HtPasswdAuth
Feb 18 15:00:57 dest python[42071]:   File "/opt/swizzin/core/htpasswd.py", line 12, in <module>
Feb 18 15:00:57 dest python[42071]:     from itsdangerous import JSONWebSignatureSerializer as Serializer
Feb 18 15:00:57 dest python[42071]: ImportError: cannot import name 'JSONWebSignatureSerializer' from 'itsdangerous' (/opt/.venv/swizzin/lib/python3.8/site-packages/itsd>
Feb 18 15:00:57 dest systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 15:00:57 dest systemd[1]: panel.service: Failed with result 'exit-code'.

```

**Comment by dctorrent1337** [comment]
It seems that itsdangerous have deprecated the JWS support:
https://itsdangerous.palletsprojects.com/en/2.0.x/jws/

Manually downgrading the package did temporarily fix the problem:

```
(swizzin) root@dest:/opt/swizzin# pip install 'itsdangerous==2.0.0'
Collecting itsdangerous==2.0.0
  Downloading itsdangerous-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: itsdangerous
  Attempting uninstall: itsdangerous
    Found existing installation: itsdangerous 2.1.0
    Uninstalling itsdangerous-2.1.0:
      Successfully uninstalled itsdangerous-2.1.0
Successfully installed itsdangerous-2.0.0
(swizzin) root@dest:/opt/swizzin# systemctl start panel
(swizzin) root@dest:/opt/swizzin# systemctl status panel
● panel.service - swizzin panel service
     Loaded: loaded (/etc/systemd/system/panel.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-02-18 15:23:16 CST; 1min 5s ago
   Main PID: 2725 (python)
      Tasks: 1 (limit: 9463)
     Memory: 40.0M
     CGroup: /system.slice/panel.service
             └─2725 /opt/.venv/swizzin/bin/python swizzin.py

Feb 18 15:23:16 dest systemd[1]: Started swizzin panel service.

```

**Comment by brettpetch** [comment]
We are aware and will be pushing a more permanent patch soon. 

/b

**Comment by frankebobdk** [comment]
Sorry for reopening this issue but after updating Swizzin a few hours ago, my panel doesn't work. Have tried to uninstall and install panel again, but no luck. This is the error code I receive: 

Feb 19 07:56:24 10925237 systemd[1]: Started swizzin panel service.
Feb 19 07:56:24 10925237 python[3872175]: Traceback (most recent call last):
Feb 19 07:56:24 10925237 python[3872175]:   File "swizzin.py", line 3, in <module>
Feb 19 07:56:24 10925237 python[3872175]:     from core.htpasswd import HtPasswdAuth
Feb 19 07:56:24 10925237 python[3872175]:   File "/opt/swizzin/core/htpasswd.py", line 13, in <module>
Feb 19 07:56:24 10925237 python[3872175]:     from authlib.jose import JsonWebSignature as Serializer
Feb 19 07:56:24 10925237 python[3872175]: ModuleNotFoundError: No module named 'authlib'
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Failed with result 'exit-code'.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Service RestartSec=100ms expired, scheduling restart.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Scheduled restart job, restart counter is at 5.
Feb 19 07:56:24 10925237 systemd[1]: Stopped swizzin panel service.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Start request repeated too quickly.
Feb 19 07:56:24 10925237 systemd[1]: panel.service: Failed with result 'exit-code'.
Feb 19 07:56:24 10925237 systemd[1]: Failed to start swizzin panel service.
