### ISSUE TITLE
[BUG] Panel will not start on fresh install (502 bad gateway)

### ISSUE THREAD

**Issue by Mikkersen** [swizzin/swizzin#944]
### What happened?

The panel does not work on a freshly install of Swizzin

Steps to reproduce:

1. Installing Swizzin including nginx and Panel
2. Going to box IP gives 502 bad gateway

Expected results:
I expected the Panel to be started and working in the browser

I tried rebooting and running: `box update` and `box upgrade panel` but are still facing the same issue

Output of `systemctl status panel`:

```
× panel.service - swizzin panel service
     Loaded: loaded (/etc/systemd/system/panel.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-12-29 14:30:47 UTC; 1min 58s ago
    Process: 1129 ExecStart=/opt/.venv/swizzin/bin/python swizzin.py (code=exited, status=1/FAILURE)
   Main PID: 1129 (code=exited, status=1/FAILURE)
        CPU: 2.063s

Dec 29 14:30:47 linux systemd[1]: panel.service: Scheduled restart job, restart counter is at 6.
Dec 29 14:30:47 linux systemd[1]: Stopped swizzin panel service.
Dec 29 14:30:47 linux systemd[1]: panel.service: Consumed 2.063s CPU time.
Dec 29 14:30:47 linux systemd[1]: panel.service: Start request repeated too quickly.
Dec 29 14:30:47 linux systemd[1]: panel.service: Failed with result 'exit-code'.
Dec 29 14:30:47 linux systemd[1]: Failed to start swizzin panel service.
```

Output of `journalctl -u panel`:

```
Dec 29 14:26:56 linux systemd[1]: Started swizzin panel service.
Dec 29 14:26:57 linux python[21259]: Traceback (most recent call last):
Dec 29 14:26:57 linux python[21259]:   File "/opt/swizzin/swizzin.py", line 55, in <module>
Dec 29 14:26:57 linux python[21259]:     limiter = Limiter(
Dec 29 14:26:57 linux python[21259]: TypeError: Limiter.__init__() got multiple values for argument 'key_func'
Dec 29 14:26:57 linux systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 14:26:57 linux systemd[1]: panel.service: Failed with result 'exit-code'.
Dec 29 14:26:57 linux systemd[1]: panel.service: Consumed 1.183s CPU time.
Dec 29 14:26:57 linux systemd[1]: panel.service: Scheduled restart job, restart counter is at 1.
Dec 29 14:26:57 linux systemd[1]: Stopped swizzin panel service.
Dec 29 14:26:57 linux systemd[1]: panel.service: Consumed 1.183s CPU time.
Dec 29 14:26:57 linux systemd[1]: Started swizzin panel service.
Dec 29 14:26:59 linux python[21536]: Traceback (most recent call last):
Dec 29 14:26:59 linux python[21536]:   File "/opt/swizzin/swizzin.py", line 55, in <module>
Dec 29 14:26:59 linux python[21536]:     limiter = Limiter(
Dec 29 14:26:59 linux python[21536]: TypeError: Limiter.__init__() got multiple values for argument 'key_func'
Dec 29 14:26:59 linux systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 14:26:59 linux systemd[1]: panel.service: Failed with result 'exit-code'.
Dec 29 14:26:59 linux systemd[1]: panel.service: Consumed 2.255s CPU time.
Dec 29 14:27:00 linux systemd[1]: panel.service: Scheduled restart job, restart counter is at 2.
Dec 29 14:27:00 linux systemd[1]: Stopped swizzin panel service.
Dec 29 14:27:00 linux systemd[1]: panel.service: Consumed 2.255s CPU time.
Dec 29 14:27:00 linux systemd[1]: Started swizzin panel service.
Dec 29 14:27:01 linux python[21537]: Traceback (most recent call last):
Dec 29 14:27:01 linux python[21537]:   File "/opt/swizzin/swizzin.py", line 55, in <module>
Dec 29 14:27:01 linux python[21537]:     limiter = Limiter(
Dec 29 14:27:01 linux python[21537]: TypeError: Limiter.__init__() got multiple values for argument 'key_func'
Dec 29 14:27:01 linux systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 14:27:01 linux systemd[1]: panel.service: Failed with result 'exit-code'.
Dec 29 14:27:01 linux systemd[1]: panel.service: Consumed 1.203s CPU time.
Dec 29 14:27:01 linux systemd[1]: panel.service: Scheduled restart job, restart counter is at 3.
Dec 29 14:27:01 linux systemd[1]: Stopped swizzin panel service.
Dec 29 14:27:01 linux systemd[1]: panel.service: Consumed 1.203s CPU time.
Dec 29 14:27:01 linux systemd[1]: Started swizzin panel service.
Dec 29 14:27:03 linux python[21538]: Traceback (most recent call last):
Dec 29 14:27:03 linux python[21538]:   File "/opt/swizzin/swizzin.py", line 55, in <module>
Dec 29 14:27:03 linux python[21538]:     limiter = Limiter(
Dec 29 14:27:03 linux python[21538]: TypeError: Limiter.__init__() got multiple values for argument 'key_func'
Dec 29 14:27:03 linux systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 14:27:03 linux systemd[1]: panel.service: Failed with result 'exit-code'.
Dec 29 14:27:03 linux systemd[1]: panel.service: Consumed 1.939s CPU time.
Dec 29 14:27:03 linux systemd[1]: panel.service: Scheduled restart job, restart counter is at 4.
Dec 29 14:27:03 linux systemd[1]: Stopped swizzin panel service.
Dec 29 14:27:03 linux systemd[1]: panel.service: Consumed 1.939s CPU time.
Dec 29 14:27:03 linux systemd[1]: Started swizzin panel service.
Dec 29 14:27:05 linux python[21540]: Traceback (most recent call last):
Dec 29 14:27:05 linux python[21540]:   File "/opt/swizzin/swizzin.py", line 55, in <module>
Dec 29 14:27:05 linux python[21540]:     limiter = Limiter(
Dec 29 14:27:05 linux python[21540]: TypeError: Limiter.__init__() got multiple values for argument 'key_func'
Dec 29 14:27:05 linux systemd[1]: panel.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 14:27:05 linux systemd[1]: panel.service: Failed with result 'exit-code'.
Dec 29 14:27:05 linux systemd[1]: panel.service: Consumed 1.538s CPU time.
Dec 29 14:27:05 linux systemd[1]: panel.service: Scheduled restart job, restart counter is at 5.
Dec 29 14:27:05 linux systemd[1]: Stopped swizzin panel service.
Dec 29 14:27:05 linux systemd[1]: panel.service: Consumed 1.538s CPU time.
Dec 29 14:27:05 linux systemd[1]: panel.service: Start request repeated too quickly.
```

### Swizzin commit

448031a

### What OS are you using?

Ubuntu 22.04 (Jammy)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
Thanks for the logs. The flask rate limiting dependency just had an update to version 3 which includes a breaking change in how the limiter was previously loaded. 

I'll need to fix the way the limiter is loaded, but if you're looking for a quick work-around, turning the limiter off in the config will prevent the related code from being loaded loaded and should allow the panel to start in the meantime.

**Comment by cavedog8** [comment]
Thanks.

I also had this issue now and change this to False and sorted.

if app.config['RATELIMIT_ENABLED'] == False:

**Comment by cavedog8** [comment]
Noob guide for anyone wanting.

As root 

nano /opt/swizzin/swizzin.py

Scroll down and look for if app.config['RATELIMIT_ENABLED'] == True:

Change it to if app.config['RATELIMIT_ENABLED'] == False:

Control x then y to save.

systemctl restart panel

Panel should be running now.

**Comment by Mikkersen** [comment]
@liaralabs, Thank you for pointing out the problem
@cavedog8, Thank you for the solution. 

I think a better temporarily fix would be to add this line: `RATELIMIT_ENABLED = False` in the following file: `/opt/swizzin/swizzin.cfg`

After a reboot, the Panel starts, and works in my browser

**Comment by liaralabs** [comment]
> I think a better temporarily fix would be to add this line: RATELIMIT_ENABLED = False in the following file: /opt/swizzin/swizzin.cfg

This is what I intended when I mentioned turning off the limiter in the config :slightly_smiling_face: 

It shouldn't be necessary to alter the swizzin.py to work around this for the time being.

I should have a patch prepared to fix this issue later today.

**Comment by liaralabs** [comment]
This should be fixed: https://github.com/swizzin/swizzin_dashboard/commit/70d5390782db8a9f1f8a127d464634e359877d67

**Comment by 001101** [comment]
not working
