### ISSUE TITLE
[BUG] Lounge install fails on npm config

### ISSUE THREAD

**Issue by Ogglord** [swizzin/swizzin#970]
### What happened?

The line in lounge.sh "npm -g config set user root" seems invalid.

Steps to reproduce:

1. Install package 'box install lounge' using sudo

Expected results: Lounge installed

### Swizzin commit

7ec4026

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
from my terminal: https://pastebin.com/tSug4QZb

from npm log:
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 8ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 2ms
15 timing config:load Completed in 19ms
16 timing npm:load:configload Completed in 19ms
17 timing npm:load:mkdirpcache Completed in 0ms
18 timing npm:load:mkdirplogs Completed in 0ms
19 verbose title npm config set user root
20 verbose argv "--global" "config" "set" "user" "root"
21 timing npm:load:setTitle Completed in 2ms
22 timing config:load:flatten Completed in 4ms
23 timing npm:load:display Completed in 5ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-03-31T08_19_38_579Z-
25 verbose logfile /root/.npm/_logs/2023-03-31T08_19_38_579Z-debug-0.log
26 timing npm:load:logFile Completed in 7ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 36ms
30 info config set "user" "root"
31 timing command:config Completed in 3ms
32 verbose stack Error: `user` is not a valid npm option
32 verbose stack     at Config.set (/usr/lib/node_modules/npm/lib/commands/config.js:158:15)
32 verbose stack     at Config.exec (/usr/lib/node_modules/npm/lib/commands/config.js:120:22)
32 verbose stack     at Config.cmdExec (/usr/lib/node_modules/npm/lib/base-command.js:130:17)
32 verbose stack     at Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:154:20)
32 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)
33 verbose cwd /home/{redacted}
34 verbose Linux 5.10.0-21-amd64
35 verbose node v18.15.0
36 verbose npm  v9.5.0
37 error `user` is not a valid npm option
38 verbose exit 1
39 timing npm Completed in 56ms
40 verbose code 1
41 error A complete log of this run can be found in:
41 error     /root/.npm/_logs/2023-03-31T08_19_38_579Z-debug-0.log
```

**Comment by SilentFez** [comment]
Receiving the same error
`Error: `user` is not a valid npm option`
